### ISSUE TITLE
Shared CSS Properties

### ISSUE THREAD

**Issue by cyouh95** [jcochran206/DasmotoArt#2]
It seems there are several properties shared among the 3 `h2` headings here: https://github.com/jcochran206/DasmotoArt/blob/master/DasmotoArts/resources/css/style.css#L12-L34

Instead of specifying all those properties for each of the headings separately, you could factor them out and use `h2` as the selector to specify them for all 3 headings at once:
```css
h2 {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```
